version: '3.1'
services:
  web:
    image: php:7.2-apache
    ports:
      - "80:8080"
    environment:
      - USERNAME=@usr
      - PASSWORD=@passwd
    volumes:
      - ./website:/var/www/html/
    networks:
      - shared-network
networks:
  shared-network: 
